CREATE TABLE BUSES (
 "ID" NUMBER(10,0) PRIMARY KEY,
 "SEATS_NUMBER" NUMBER(10,0)
);

CREATE TABLE TRANSPORTS (
  "ID" NUMBER(10,0) PRIMARY KEY ,
  "NAME" VARCHAR2(100),
  "PRICE" NUMBER(10,0),
  "AVAILABILITY" NUMBER(1,0),
  "PRODUCER_ID" NUMBER(10,0)
 );

CREATE TABLE PRODUCERS (
  "ID" NUMBER(10,0) PRIMARY KEY,
	"NAME" VARCHAR2(50)
);

CREATE TABLE CARGO (
  "ID" NUMBER(10,0) PRIMARY KEY,
	"BODY_TYPE" VARCHAR2(50)
);

CREATE TABLE CARS (
  "ID" NUMBER(10,0) PRIMARY KEY ,
	"MILEAGE_KM" NUMBER(10,0),
	"ENGINE_CAPACITY" NUMBER(10,0)
);

CREATE TABLE MOTORCYCLES (
  "ID" NUMBER(10,0) PRIMARY KEY,
  "ISSUE_YEAR" NUMBER(10,0)
);

CREATE TABLE SALONS (
  "ID" NUMBER(10,0) PRIMARY KEY ,
	"NAME" VARCHAR2(50),
	"TRANSPORT_ID" NUMBER(10,0)
);

CREATE TABLE SENSORS (
  "ID" NUMBER(10,0) PRIMARY KEY,
	"NAME" VARCHAR2(50)
);

CREATE TABLE SENSOR_TRANSPORT (
  "SENSOR_ID" NUMBER(10,0) ,
	"TRANSPORT_ID" NUMBER(10,0),
  CONSTRAINT constraint_name PRIMARY KEY (SENSOR_ID, TRANSPORT_ID)
);

ALTER TABLE BUSES ADD
	CONSTRAINT FK_BUS_TRANSPORT
		FOREIGN KEY (ID)
			REFERENCES TRANSPORTS (ID);

ALTER TABLE CARGO ADD
  CONSTRAINT FK_CARGO_TRANSPORT
    FOREIGN KEY (ID)
      REFERENCES TRANSPORTS (ID);

ALTER TABLE MOTORCYCLES ADD
  CONSTRAINT FK_MOTORCYCLE_TRANSPORT
    FOREIGN KEY (ID)
      REFERENCES TRANSPORTS (ID);

ALTER TABLE CARS ADD
  CONSTRAINT FK_CAR_TRANSPORT
    FOREIGN KEY (ID)
      REFERENCES TRANSPORTS (ID);

ALTER TABLE SALONS ADD
  CONSTRAINT FK_SALON_TRANSPORT
  FOREIGN KEY (TRANSPORT_ID)
    REFERENCES TRANSPORTS (ID);

ALTER TABLE TRANSPORTS ADD
	CONSTRAINT FK_TRANSPORT_PRODUCER
		FOREIGN KEY (PRODUCER_ID)
			REFERENCES PRODUCERS(ID);

ALTER TABLE SENSOR_TRANSPORT ADD
  CONSTRAINT FK_TRANSPORTS
    FOREIGN KEY (TRANSPORT_ID)
      REFERENCES TRANSPORTS(ID);

ALTER TABLE SENSOR_TRANSPORT ADD
  CONSTRAINT FK_SENSORS
    FOREIGN KEY (SENSOR_ID)
      REFERENCES SENSORS(ID);

CREATE SEQUENCE PRODUCERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE TRANSPORTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SALONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SENSORS_SEQ START WITH 1 INCREMENT BY 1;